feat: TokenSelect Component Support Multiple and Tags Mode
ant-design/ant-design-web3 pull request #1049
Opened 2024-07-15 14:15 UTC by MarioJames

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design-web3/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

## 💡 Background and solution

TokenSelect Component Support Multiple and Tags Mode

![image](https://github.com/user-attachments/assets/cc69ec4d-42f5-4286-a77f-48dbd3779387)

## 🔗 Related issue link

2024-07-15 14:19 UTC, gin-lsl requested changes

2024-07-15 14:19 UTC, gin-lsl commented on packages/web3/src/token-select/index.tsx
> +      {!hideName && <span className="token-name">{token.name}</span>}
classname 加个前缀呗

2024-07-15 14:23 UTC, thinkasany commented
lock文件咋变化这么大 好像也没安装啥新的东西，是pnpm版本非8.9.0么，目前有限制这个版本

2024-07-15 14:26 UTC, thinkasany commented on .changeset/nasty-windows-tie.md
> +feature: TokenSelect Component Support Multiple and Tags Mode
```suggestion
feat: TokenSelect Component Support Multiple and Tags Mode
```

2024-07-15 14:29 UTC, thinkasany commented on packages/web3/src/token-select/index.md
> +### Not Fount Token
```suggestion
### Not Found Token
```

2024-07-15 14:36 UTC, thinkasany commented on packages/web3/src/token-select/demos/multipltSelect.tsx
> +        mode="tags"
```suggestion
        mode="multiple"
```

2024-07-15 14:47 UTC, thinkasany commented on packages/web3/src/token-select/demos/multipltSelect.tsx
> +        mode="tags"
文件名好像也有个错别字

2024-07-16 00:23 UTC, gin-lsl commented on packages/web3/src/token-select/index.tsx
>    tokenList,
这个 `tokenList` 是不是可以改成 `options`？

2024-07-16 03:06 UTC, MarioJames commented on packages/web3/src/token-select/index.tsx
>    tokenList,
> 这个 `tokenList` 是不是可以改成 `options`？

可以改，但这个 `tokenList` 应该还要保留一下（加个 `deprecated` 标识好了），怕对线上使用产生影响

2024-07-16 03:07 UTC, MarioJames commented
> 1. lock文件咋变化这么大 好像也没安装啥新的东西，是pnpm版本非8.9.0么，目前有限制这个版本，可以再看看
> 2. `pnpm run test:update` 更新一下snap
> 
> <img alt="image" width="716" src="https://private-user-images.githubusercontent.com/117748716/348741058-4c0db3f3-87cb-4f88-81b6-0871aad89b6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwOTkzOTAsIm5iZiI6MTcyMTA5OTA5MCwicGF0aCI6Ii8xMTc3NDg3MTYvMzQ4NzQxMDU4LTRjMGRiM2YzLTg3Y2ItNGY4OC04MWI2LTA4NzFhYWQ4OWI2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQwMzA0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDUyNTVkMDJlNTg2NTM2YTVhNmJkNWYxODg1ODhiMDYwYzZiNjI5NTJkZjgyNTk3ZDhkNGQzMGU0NzZhNzEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AzgnfrbN3Gm6IIaPZ1254nIUg3wa7ToNpaOVjKHqVkc">

我就本地跑了下 `pnpm i` 其他操作没做，不清楚为啥会出现这么大差异

2024-07-16 03:16 UTC, thinkasany commented
> > 1. lock文件咋变化这么大 好像也没安装啥新的东西，是pnpm版本非8.9.0么，目前有限制这个版本，可以再看看
> > 2. `pnpm run test:update` 更新一下snap
> > 
> > <img alt="image" width="716" src="https://private-user-images.githubusercontent.com/117748716/348741058-4c0db3f3-87cb-4f88-81b6-0871aad89b6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwOTkzOTAsIm5iZiI6MTcyMTA5OTA5MCwicGF0aCI6Ii8xMTc3NDg3MTYvMzQ4NzQxMDU4LTRjMGRiM2YzLTg3Y2ItNGY4OC04MWI2LTA4NzFhYWQ4OWI2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQwMzA0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDUyNTVkMDJlNTg2NTM2YTVhNmJkNWYxODg1ODhiMDYwYzZiNjI5NTJkZjgyNTk3ZDhkNGQzMGU0NzZhNzEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AzgnfrbN3Gm6IIaPZ1254nIUg3wa7ToNpaOVjKHqVkc">
> 
> 我就本地跑了下 `pnpm i` 其他操作没做，不清楚为啥会出现这么大差异

你本地pnpm版本应该不是8.9.0，应该是 >9 or lastest, 所以整个lockfile格式都变了。既然没有安装新的包还是比较好处理的，直接撤掉lockfile的修改，或者就是本地用pnpm 8.9.0去安装。
![image](https://github.com/user-attachments/assets/1522fc0c-7073-4138-9014-9bf7d5dbee4b)

2024-07-16 07:16 UTC, thinkasany commented
要不然直接去main分支复制一下lock文件，提交一个commit上去好了，这样子就没冲突了 😁

2024-07-18 06:00 UTC, thinkasany commented on packages/web3/src/token-select/__tests__/index.test.tsx
> +import { COMPONENT_NAME, TokenSelect } from '..';
其他地方好像都是通过getPrefixCls的方式来的，考虑一下风格上的统一不
![image](https://github.com/user-attachments/assets/b4be6ff6-33b1-488e-aa90-06f7a7750546)

2024-07-18 07:48 UTC, thinkasany commented
tag模式下，输入一个不存在的，antd select组件会生成一个新的tag，但是这边会出现一个错误。
![image](https://github.com/user-attachments/assets/62d15180-2d54-43b4-9668-b25117d3f06d)
![image](https://github.com/user-attachments/assets/8ba1168d-af37-4f42-a408-071e65c1304c)

2024-07-19 02:45 UTC, MarioJames commented
> tag模式下，输入一个不存在的，antd select组件会生成一个新的tag，但是这边会出现一个错误。 ![image](https://private-user-images.githubusercontent.com/117748716/349863827-62d15180-2d54-43b4-9668-b25117d3f06d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTczOTMsIm5iZiI6MTcyMTM1NzA5MywicGF0aCI6Ii8xMTc3NDg3MTYvMzQ5ODYzODI3LTYyZDE1MTgwLTJkNTQtNDNiNC05NjY4LWIyNTExN2QzZjA2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQwMjQ0NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMjU5YjIxOWViN2UyYWNhMzgxNDQxZDg1MjIzOTMxYzgzMDQxNjk2ZTkyOWQyYmU4OTk0M2NjYTViNzQwYjhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zSHUvsbuVX1HP_xiMWZuua-2qYdPEnN6offl0YUkyS0) ![image](https://private-user-images.githubusercontent.com/117748716/349863277-8ba1168d-af37-4f42-a408-071e65c1304c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTczOTMsIm5iZiI6MTcyMTM1NzA5MywicGF0aCI6Ii8xMTc3NDg3MTYvMzQ5ODYzMjc3LThiYTExNjhkLWFmMzctNGY0Mi1hNDA4LTA3MWU2NWMxMzA0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQwMjQ0NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDQ1NTdiN2RmZWY5MTVlMTc4ZTFiMzQwZTAyODQ4Njc5ZTc3MDJiYjA3ZmIzZGE3OGUxZWE4ZWEyMDg1Y2JiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bP7GQl7PntXh80XmhDZOlDGtQclWnCe1GMvU39XDYOs)

我这边去掉 tag 模式吧，我们这个场景不能让他随便输入

2024-07-19 02:51 UTC, thinkasany commented
如果去掉tags的话，ts这边也补一下吧，否则默认走antd的类型推荐，用户还是容易误用

![image](https://github.com/user-attachments/assets/d26bc4c4-5c68-42c7-8b72-1097c3a71113)
![image](https://github.com/user-attachments/assets/4c4211f4-5318-4692-90bd-59807bcd21a5)

2024-07-19 03:16 UTC, MarioJames commented
> 如果去掉tags的话，ts这边也补一下吧，否则默认走antd的类型推荐，用户还是容易误用
> 
> ![image](https://private-user-images.githubusercontent.com/117748716/350208925-d26bc4c4-5c68-42c7-8b72-1097c3a71113.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTkyNTYsIm5iZiI6MTcyMTM1ODk1NiwicGF0aCI6Ii8xMTc3NDg3MTYvMzUwMjA4OTI1LWQyNmJjNGM0LTVjNjgtNDJjNy04YjcyLTEwOTdjM2E3MTExMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQwMzE1NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOWU0MDA0NTJjOGY1NDA0NTZiOTA0OWUwNGJmNWYwMjJhZGI1MWQyZjM5NWMyOTEzNDcxM2YyMmRkYjk0NzdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-nWAsmiwfaUowtAs5SSw5-FM5kMvONKIF-0r9cuxVRI) ![image](https://private-user-images.githubusercontent.com/117748716/350209064-4c4211f4-5318-4692-90bd-59807bcd21a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTkyNTYsIm5iZiI6MTcyMTM1ODk1NiwicGF0aCI6Ii8xMTc3NDg3MTYvMzUwMjA5MDY0LTRjNDIxMWY0LTUzMTgtNDY5Mi05MGJkLTU5ODA3YmNkMjFhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQwMzE1NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOWJhMDBhNTAzMDg1NmExYzk4NWEyOWM0NzdiNzRhMTVkNTY0MzJiNjlkZTQ2MTIzMzhjMmE5NmMwMWEwOTE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ain2zu527Z033FUgSVDCj-BG5GlPWFisrfnBPez69ns)

嗯嗯 已经重写了 只支持 `multiple`

2024-07-19 03:52 UTC, thinkasany commented on packages/web3/src/token-select/index.zh-CN.md
> +| tokenList | 可选择的代币列表，已弃用，请使用 `options` API | [Token](/components/types-cn#token)[] | - | - |
在代码里面加个废弃警告吧，参考之前的使用，可以直接在控制台给用户暴露出来错误。
```
  const warning = devUseWarning('ConnectModal');
  warning.deprecated(!('groupOrder' in restProps), 'groupOrder', 'group={{groupOrder: ()=> {}}}'); 
```

2024-07-19 06:08 UTC, yutingzhao1991 commented
LGFM

2024-07-19 07:00 UTC, thinkasany commented on .changeset/nasty-windows-tie.md
> +feat: TokenSelect Component Support Multiple and Tags Mode
既然仅支持这个Multiple 的话，这里changelog是不是得改一下

2024-07-19 07:14 UTC, gin-lsl approved these changes

2024-07-19 07:17 UTC, merged