refactor: modify address code & add APIS from docs & add test
ant-design/ant-design-web3 pull request #507
Opened 2024-01-17 10:52 UTC by shanchuan1

2024-01-17 13:13 UTC, thinkasany commented on packages/web3/src/address/index.zh-CN.md
> +<code src="./demos/customTooltip.tsx"></code>
补充demo的时候，参考一下 ConnectButton吧，包括demo的文件名，而且你这边漏了英文文档的。

2024-01-17 13:13 UTC, thinkasany commented on packages/web3/src/address/__tests__/index.test.tsx
> -    expect(() => render(<Address />)).not.toThrow();
为啥要删掉这个用例呢？

2024-01-17 13:13 UTC, thinkasany commented on packages/web3/src/address/index.tsx
> +    if (isValidElement(tooltip) || typeof tooltip === 'string') {
这边改动需要 @yutingzhao1991 看看，你这边改动有点大了，涉及api了，和ConnectButton不太一样

<img width="578" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/117748716/047d6dfe-eb6b-4173-80f0-e819fce0b5d1">

2024-01-18 01:30 UTC, yutingzhao1991 commented on packages/web3/src/address/index.tsx
> +  // eslint-disable-next-line react-hooks/rules-of-hooks
这个是什么 lint 问题？为什么要 disable 掉？

2024-01-18 01:30 UTC, yutingzhao1991 commented on packages/web3/src/address/index.tsx
> +  const mergedTooltip = useMemo(() => {
这个简单的逻辑不需要用 useMemo 来优化，没什么性能提升，反而影响可读性。

2024-01-18 01:30 UTC, yutingzhao1991 commented on packages/web3/src/address/index.tsx
> +    if (isValidElement(tooltip) || typeof tooltip === 'string') {
API 看上去应该没什么改动

2024-01-18 01:30 UTC, yutingzhao1991 commented on packages/web3/src/address/index.tsx
> +
感觉之前这么写也没什么问题，用 useMemo 反而搞复杂了。

2024-01-18 01:57 UTC, thinkasany commented on packages/web3/src/address/index.tsx
> +
usememo确实没必要，api的改动指的是：
ConnectButton 配置title、copyable，这边是直接自己配置子组件，想问一下是不是应该保持一致还是怎么的，一个组件一个用法的话，感觉使用起来不是很习惯。
![image](https://github.com/ant-design/ant-design-web3/assets/117748716/7f5b9992-916c-4425-8614-82c737ea26b7)

2024-01-18 02:03 UTC, thinkasany commented on packages/web3/src/address/index.tsx
> +    if (isValidElement(tooltip) || typeof tooltip === 'string') {
api的改动指的是：
ConnectButton 配置title、copyable，这边是直接自己配置子组件，想问一下是不是应该保持一致还是怎么的，一个组件一个用法的话，感觉使用起来不是很习惯。
![image](https://github.com/ant-design/ant-design-web3/assets/117748716/7f5b9992-916c-4425-8614-82c737ea26b7)

2024-01-18 05:36 UTC, shanchuan1 commented on packages/web3/src/address/index.tsx
> +
done，已经更改了

2024-01-18 05:51 UTC, yutingzhao1991 commented on packages/web3/src/address/index.tsx
> +    if (isValidElement(tooltip) || typeof tooltip === 'string') {
对于 Address 和 ConnectButton 来说 copyable 的意义不一样的，不是一个逻辑。Address 的 copyable 不是在 tooltip 里面。

2024-01-18 05:52 UTC, yutingzhao1991 commented on packages/web3/src/address/index.tsx
> +
解决完成的问题可以点一下下面的 Resolve 
<img width="375" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/61da9d61-f082-43ef-a3f1-adce8beec634">

2024-01-18 11:12 UTC, yutingzhao1991 approved these changes

2024-01-19 03:25 UTC, yutingzhao1991 commented on packages/web3/src/address/index.tsx
> -  address?: string;
这个应该不能改，改了就算 break change 了，不传就返回 null 就好了，感觉也没啥问题。

2024-01-19 03:25 UTC, yutingzhao1991 commented on packages/web3/src/address/index.tsx
> +    console.error('"address" property of the "Address" is required');
address 如果是不必选的，那这里也不要报错吧，就返回 null 就好了。

2024-01-19 03:27 UTC, yutingzhao1991 requested changes
address 改一下，还是非 required 吧

2024-01-19 03:47 UTC, yutingzhao1991 approved these changes

2024-01-19 03:48 UTC, merged