文档:img添加alt默认字段，格式化表格
ant-design/ant-design-web3 pull request #694
Opened 2024-03-25 08:58 UTC by zhouyou12

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design-web3/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

## 📝 Git Commit Message Convention

> This is adapted from [Angular's commit convention](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular).

## 🔗 Related issue link

2024-03-25 09:00 UTC, kiner-tang commented on docs/course/contract-compile-deploy.md
> +<img src='./img/changeNode.png' width="33%" alt="">
既然加了 alt 属性，就不要弄空字符串吧，根据图片内容写个概要放在 alt 里面

2024-03-26 02:31 UTC, jeasonstudio requested changes
PR title 需要改为符合 commit lint 格式的英文标题，squash merge 后风格统一

2024-03-26 03:15 UTC, thinkasany commented on docs/course/contract-compile-deploy.md
> +<img src='./img/changeNode.png' width="33%" alt="">
```suggestion
<img src='./img/changeNode.png' width="33%" alt="choose Injected Provider - MetaMask" />
```

2024-03-26 03:15 UTC, thinkasany commented on docs/course/contract-compile-deploy.md
> +<img src='./img/connect1.png' width="33%" alt="">
```suggestion
<img src='./img/connect1.png' width="33%" alt="connecting MetaMask to Remix" />
```

2024-03-26 03:15 UTC, thinkasany commented on docs/course/contract-compile-deploy.md
> +<img src='./img/connect2.png' width="33%" alt="">
```suggestion
<img src='./img/connect2.png' width="33%" alt="display the connected network and account" />
```

2024-03-26 03:15 UTC, thinkasany commented on docs/course/contract-compile-deploy.zh-CN.md
> +<img src='./img/connect2.png' width="33%" alt="">
```suggestion
<img src='./img/changeNode.png' width="33%" alt="选择 Injected Provider - MetaMask" />
<img src='./img/connect1.png' width="33%" alt="将 MetaMask 连接到 Remix" />
<img src='./img/connect2.png' width="33%" alt="显示连接的网络和账户" />
```

2024-03-26 03:24 UTC, thinkasany approved these changes

2024-03-26 03:28 UTC, jeasonstudio approved these changes

2024-03-26 03:28 UTC, merged

2024-03-26 03:29 UTC, thinkasany commented
@zhouyou12 Thanks for your contribution!